### ISSUE TITLE
Xem danh sách món ăn

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#12]
- Hiển thị: màn hình danh sách món ăn xuất hiện kế bên menu danh sách món ăn sẽ hiện ra khi nhân viên bấm vào order, món ăn được liệt kê theo dạng dánh sách.
- Xử lý: hệ thống sẽ thực hiện câu lệnh để xuất danh sách món ăn ra màn hình.
- Lưu trữ: không.
--

**Comment by TinPham110902** [comment]
đã nhận

**Comment by hungnguyenquang221** [comment]
đã nhận

**Comment by hungnguyenquang221** [comment]
Đã xong
