### ISSUE TITLE
Thanh toán

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#17]
hiển thị: 
-màn hình hiển thị danh sách các món ăn đã chọn theo dạng list
-môi ô món ăn trong danh sách món ăn đã chọn ở ngoài cùng bên ngoài sẽ là giá tiền gốc của món ăn kế bên là số lượng hiện thị với dạng như x1, x2, x3 và ngay phía dưới sẽ hiện số tiền tổng là số tiền gốc nhân với số lượng món ăn
-dưới danh sách món ăn hiển thị số tiền cuối cùng nằm cùng bên với chỗ hiện số tiền ở phía trên
-ở phía dưới sẽ có các ô phương thức thanh toán là tiền mặt, momo
-phía dưới chọn phương thức sẽ có button "hoàn tất thanh toán" nằm ở dưới cùng bên phải và button "hủy" nằm ở phía dưới cùng bên trái đối xứng với button "hoàn tất thanh toán"
xử lý: hệ thống sẽ thực câu lệnh tính tổng số tiền, chuyển nội dung thanh toán vào một file pdf tạo thành 1 hóa đơn
lưu trữ: lưu trữ hóa đơn

**Comment by TinPham110902** [comment]
đã nhận
