### ISSUE TITLE
Tra cứu món ăn

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#18]
hiển thị: ô tìm kiếm nằm ở phía trên cùng phía bên phải nằm ở trên danh sách món ăn, kế bên sẽ có một button với nội dung là "search", 
xử lý: thực hiện câu lệnh để tìm kiếm món ăn đã nhập trên ô tìm kiếm trong database sau đó xuất hiện lên màn hình
lưu trữ: không

**Comment by TinPham110902** [comment]
đã xong
