### ISSUE TITLE
Xóa món ăn

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#22]
- Hiển thị: không có.
-  Xử lý: sau khi bấm vào biểu tượng thùng rác ở trong món ăn của menu món ăn, hệ thống sẽ thực hiện câu lệnh xóa món ăn đó khỏi dữ liệu.
-  Lưu trữ: không.

**Comment by hungnguyenquang221** [comment]
Đã nhận

**Comment by luulyha** [comment]
> [Mar 30, 2023](#event-8879008732)

**Comment by hungnguyenquang221** [comment]
Đã xong
