### ISSUE TITLE
Sắp xếp món ăn

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#23]
Hiển thị : ở phía trên menu có các thanh tab lựa chọn sắp xếp món ăn theo thể loại như gà, pizza,...
Xử lý : hệ thống sẽ thực hiện câu lệnh chọn lọc ra thể thoại món ăn để sắp xếp vào các tab 
Lưu trữ : không

**Comment by luulyha** [comment]
đã nhận

**Comment by TinPham110902** [comment]
Đã xong
