### ISSUE TITLE
Thêm combo món ăn

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#24]
Hiển thị: chia màn hình thành 2 phần 
bên trái là danh sách các món ăn thể hiện lần lượt từ trên xuống dưới là hình, tên, giá, hình giỏ hàng
bên phải là bản danh sách món ăn được thêm vào combo thể hiện theo dạng bảng bao gồm các cột 
-Tên sản phẩm
-Hình thể hiện hình của món ăn
-Giá giá của một món ăn
-Số Lượng phía dưới ô nhập số lượng sẽ có 1 nút update quanlity
-Tổng thể thiện tổng số tiền tương ứng với số lượng
-Xóa để chữ Remove ở cột này với mỗi món ăn
ở phía trên bảng gồm số lượng món án và trên combo
dưới 2 cái trên là nói thêm ảnh
tiếp theo là ô nhập số tiền kế bên ô nhập số tiền nó button là tạo
Xử lý: khi bấm vào giỏ hàng ở ô món ăn tưởng ứng thì món ăn đó sẽ xuất hiện bỏ bảng bên trái
-Khi bấm vào chữ Remove thì sẽ xóa món ăn ra khỏi bản
-Nhập số lượng món ăn rồi sau đó bấm update quantity sẽ cập nhập lại giá tổng 
lưu trữ: dữ liệu Tên combo, số tiền, hình ảnh vào bảng Combo
Lưu Mã món ăn, số lượng vào bảng CT_combo

**Comment by HuynhNgocAnh22** [comment]
Đã nhận

**Comment by HuynhNgocAnh22** [comment]
Đã xong
