### ISSUE TITLE
Nhập tồn đầu

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#28]
- Hiển thị: màn hình chỉnh sửa món ăn thêm vào 1 ô nhập tồn đầu phía dưới ô giá món ăn.
- Xử lý: hệ thống sẽ thực hiện câu lệnh lưu lại câu lệnh sau đó cập nhật lên lại menu món ăn.
- Lưu trữ: lưu trữ lại số lượng tồn đầu vào trong database.

**Comment by hungnguyenquang221** [comment]
Đã nhận

**Comment by hungnguyenquang221** [comment]
Đã xong
