### ISSUE TITLE
Xem menu

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#32]
- Hiển thị: màn hình xuất hiện các props theo dạng lưới, mỗi props chứa hình ảnh món ăn ở phía trên, phía dưới mô tả món ăn bao gồm tên món ăn, size, góc dưới bên phải của mỗi props chứa thông tin giá của món ăn  trong props đó
- Xử lý: không
- Lưu trữ: không có

**Comment by HuynhNgocAnh22** [comment]
Đã nhận

**Comment by hungnguyenquang221** [comment]
Đã xong

**Comment by HuynhNgocAnh22** [comment]
Đã xong
