### ISSUE TITLE
Xem khuyến mãi hàng ngày

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#33]
Giao diện : Sẽ hiện thị dưới dạng các slider 
Xử lý: Lấy dữ liệu từ bảng dữ liệu Khuyến mãi và Sử dụng Carousel để hiện thị tự động các ảnh khuyển mãi
Lưu trữ: Không

**Comment by pphibangg** [comment]
Đã nhận
