### ISSUE TITLE
Xem món ăn theo loại món

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#34]
Hiển thị: 
- hiển thị tên loại ở phía trên cùng bên trái
- danh sách món ăn theo dạng list môi ô có hình ảnh món ăn nằm ở trên phía dưới là tên món ăn và giá tiền nằm theo hàng dọc.
Xử lý: hệ thống tìm kiếm tên loại món ăn tương ứng để xuất lên màn hình
Lưu trữ: không

**Comment by TinPham110902** [comment]
đã nhận

**Comment by TinPham110902** [comment]
Đã xong
