### ISSUE TITLE
Tìm kiếm tài khoản

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#35]
Hiển thị:ô  tìm kiếm món ăn nằm ở trên cùng bên phải trong thanh navbar kế bên ô tìm kiếm có button nội dùng là "tìm".
Xử lý: hệ thống thực hiện câu lệnh tìm kiếm tên tài khoản đã nhập trong database sau đó hiển thị lên danh sách tài khoản
lưu trữ: không.

**Comment by TinPham110902** [comment]
đã nhận

**Comment by TinPham110902** [comment]
đã xong
