### ISSUE TITLE
Xem món ăn bán chạy nhất

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#36]
Giao diện: Hiển thị bảng gồm 2 cột Tên món ăn và số lượng được sắp xếp từ lớn đến bé
Xử lý: Lấy thông tin từ bảng CT_HD rồi tổng hợp lại số lượng và sắp xếp từ lớn đến bé hiện thị lên màn hình
Lưu trữ: không

**Comment by pphibangg** [comment]
đã nhận
