### ISSUE TITLE
Thêm tài khoản nhân viên 

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#5]
Hiển thị: 
ở trên cùng hiển thị text Add User và phía dưới là màn hình xuất hiện các ô nhập thông tin bao gồm:
-User Role
-Employee Name
-Status
-User Name
-Password
-Confirm Password
-Ở dưới cùng bên phải là button "Thoát" kế bên là button "Tiếp tục"
xử lý: hệ thống sẽ kiểm tra xem tài khoản đã tồn tại hay chưa nếu chưa thì hệ thống sẽ thực hiện câu lệnh insert để lưu tài khoản vào trong database,  nếu không thì thông báo "tài khoản đã tồn tại" ở phía dưới ô tài khoản
lưu trữ: lưu trữ lại toàn bộ thông tin của tài khoản vừa tạo

**Comment by TinPham110902** [comment]
đã nhận

**Comment by TinPham110902** [comment]
đã xong
