### ISSUE TITLE
Xóa tài khoản nhân viên

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#6]
Giao diện: Hiển thị dưới dạng table thông tin tài khoản cho phép thêm xóa sửa 
Xử lý: Lấy thông tin từ bản tài khoản, Sau khi bấm xóa sẽ hiện thông báo bạn có chắc chắn muốn xóa tài khoản này
Lưu trữ: databaes

**Comment by pphibangg** [comment]
đã nhận
