### ISSUE TITLE
Cập nhật tài khoản nhân viên

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#7]
hiển thị: hiển thị form giống như form thêm tài khoản nhưng ô xác nhận mật khẩu và ô mật khẩu sẽ không có, còn ô tên tài khoản sẽ được làm mờ đi và không được phép chỉnh sửa. ở phía dưới cùng bên phải sẽ có button "cập nhật" nằm ở ngoài cùng bên phải và button "hủy" nằm ở dưới cùng bên trái
xử lý: thực hiện câu lệnh để cập nhật lại thông tin tài khoản ở trong database
lưu trữ: cập nhật lại thông tin cùa tài khoản

**Comment by TinPham110902** [comment]
đã nhận
