### ISSUE TITLE
Cấp quyền cho tài khoản

### ISSUE THREAD

**Issue by luulyha** [TinPham110902/CuaHangBanDoAnNhanh#8]
Hiển thị: màn hình hiển thị một Dropdown, bên cạnh các dòng chữ chức năng theo thứ tự là Add, Edit,  Delete, Grant permission(Dropdown), trong spinner có các quyền của tài khoản như Admin, Quản lý, Nhân viên
Xử lý: chọn quyền thích hợp cho tài khoản
Lưu trữ: thông tin account như username, password và permission

**Comment by HuynhNgocAnh22** [comment]
Đã nhận

**Comment by HuynhNgocAnh22** [comment]
Đã xong
